### ISSUE TITLE
Fill "Community Standards" checklist

### ISSUE THREAD

**Issue by GodHermit** [GodHermit/turing-machine#8]
- [x] Update `README.md`
- [x] Add code of conduct
- [x] Choose licence
- [x] Create issue templates
